"""
Report Generator — ForenSight AI
====================================
Builds the final structured Markdown report that the copilot returns.
Separated from copilot.py so it can be unit-tested independently and
reused by the PDF report pipeline.

Consumes pre-assembled context dicts (from services/context/) so it
has no direct database dependencies.
"""

from typing import Any, Dict, List, Optional


def build_forensic_report(
    case: Dict[str, Any],
    anomalies: List[Dict[str, Any]],
    correlations: List[Dict[str, Any]],
    enriched_techniques: List[Dict[str, Any]],
    semantic_context: List[Dict[str, Any]],
    evidence_list: Optional[List[Dict[str, Any]]] = None,
    question: Optional[str] = None,
) -> str:
    """
    Assemble a structured Markdown response from pre-fetched context.
    Tailors output to specific questions when provided, or generates full report.
    """
    lines: List[str] = []
    q_lower = (question or "").lower()

    # If user asked a specific question, check for targeted response mode
    is_evidence_query = any(k in q_lower for k in ["evidenc", "file", "upload", "attachment"])
    is_anomaly_query = any(k in q_lower for k in ["anomal", "outlier", "suspicious", "flagged"])
    is_graph_query = any(k in q_lower for k in ["graph", "connect", "relation", "parent", "chain", "correlation"])

    # ── Header ────────────────────────────────────────────────────────────────
    lines.append(f"# 🛡️ Forensic Analysis: {case.get('title', 'Investigation Case')}")
    lines.append(f"**Status:** {case.get('status', 'open').replace('_', ' ').title()}  ")
    if question:
        lines.append(f"**Question:** _{question}_\n")
    else:
        lines.append(f"**Description:** {case.get('description', 'N/A')}\n")

    # ── 1. Uploaded Evidence Files (if asked or full report) ──────────────────
    if (is_evidence_query or not question) and evidence_list is not None:
        lines.append("---\n### 📁 Uploaded Evidence Files")
        if evidence_list:
            lines.append(f"**{len(evidence_list)} evidence item(s)** uploaded for this case:\n")
            for i, ev in enumerate(evidence_list, 1):
                filename = ev.get("filename") or ev.get("original_filename") or "Unknown file"
                file_type = ev.get("file_type") or ev.get("parser_type") or "raw"
                status = ev.get("status", "unknown")
                size_kb = (ev.get("file_size_bytes") or 0) / 1024
                lines.append(
                    f"{i}. 📄 **`{filename}`** | Type: `{file_type}` | Status: `{status}` | Size: `{size_kb:.1f} KB`"
                )
        else:
            lines.append("*No evidence files have been uploaded to this case yet.*")
        lines.append("")

    # ── 2. Question Semantic Context Matches ─────────────────────────────────
    if question and semantic_context:
        lines.append("---\n### 🔍 Relevant Event Matches (FAISS Search)")
        for i, sc in enumerate(semantic_context[:5], 1):
            ts = sc.get("timestamp", "")
            lines.append(
                f"{i}. `{ts}` — **{sc.get('subject')}** → _{sc.get('action')}_ "
                f"→ **{sc.get('object')}** *(severity: {sc.get('severity')})*"
            )
        lines.append("")

    # ── 3. ML Anomaly Detections ──────────────────────────────────────────────
    if is_anomaly_query or not question:
        lines.append("---\n### 🤖 Machine Learning Anomaly Detections")
        if anomalies:
            lines.append(f"**{len(anomalies)} anomalous events** flagged by Isolation Forest:\n")
            for i, a in enumerate(anomalies[:6], 1):
                sev = (a.get("severity") or "info").upper()
                score = a.get("anomaly_score", 0.0)
                ts = a.get("timestamp", "")
                lines.append(
                    f"{i}. **[{sev}]** `{ts}` — **{a.get('subject')}** → _{a.get('action')}_ → **{a.get('object')}** (Score: `{score:.4f}`)"
                )
        else:
            lines.append("*No anomalies detected in current event set.*")
        lines.append("")

    # ── 4. Graph Correlations ────────────────────────────────────────────────
    if is_graph_query or not question:
        if correlations:
            lines.append(f"---\n### 🔗 Graph Correlations ({len(correlations)} derived relationships)")
            for c in correlations[:6]:
                lines.append(f"- **[{c.get('rule')}]** `{c.get('source')}` → `{c.get('target')}`")
            lines.append("")

    # ── 5. MITRE ATT&CK Techniques (full report mode) ───────────────────────
    if not question and enriched_techniques:
        lines.append("---\n### 🎯 MITRE ATT&CK Techniques Observed")
        for t in enriched_techniques[:5]:
            lines.append(f"- **{t['id']}** — {t['name']} *(Tactic: {t['tactic']})*")
        lines.append("")

    lines.append(
        "\n> *Generated by ForenSight AI Copilot.*"
    )

    return "\n".join(lines)
