from datetime import datetime
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field

class ReportFinding(BaseModel):
    title: str = Field(..., description="Short title describing the compromise finding")
    severity: str = Field(..., description="Finding severity level (critical, high, medium, low, info)")
    description: str = Field(..., description="Detailed description of what occurred and what evidence supports it")
    mitre_techniques: List[str] = Field(default_factory=list, description="Mapped MITRE ATT&CK technique IDs")
    evidence_citations: List[str] = Field(default_factory=list, description="List of event IDs acting as evidence backing this finding")

class ReportBase(BaseModel):
    title: str = Field(..., description="Title of the forensic investigation report")
    summary: str = Field(..., description="Executive summary generated by the AI copilot & investigator inputs")
    findings: List[ReportFinding] = Field(default_factory=list, description="List of key forensic compromise findings")
    conclusion: Optional[str] = Field(None, description="Final closing notes or cleanup instructions")

class ReportCreate(ReportBase):
    case_id: str = Field(..., description="Parent Case ID this report is based on")

class ReportUpdate(BaseModel):
    title: Optional[str] = None
    summary: Optional[str] = None
    findings: Optional[List[ReportFinding]] = None
    conclusion: Optional[str] = None

class ReportResponse(ReportBase):
    id: str = Field(..., description="The report's MongoDB ObjectId representation")
    case_id: str = Field(..., description="Parent case ID")
    organization_id: str = Field(..., description="Owner organization ID")
    pdf_minio_path: Optional[str] = Field(None, description="Path in MinIO where the compiled PDF is stored")
    created_by: str = Field(..., description="User ID of generator")
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
        json_schema_extra = {
            "example": {
                "id": "60c72b2f9b1d8b2a5c8b4572",
                "case_id": "60c72b2f9b1d8b2a5c8b4569",
                "organization_id": "60c72b2f9b1d8b2a5c8b4567",
                "title": "Incident Summary Report: Case #1029",
                "summary": "AI generated executive summary detailing lateral movement via WinRM and PowerShell script execution...",
                "findings": [
                    {
                        "title": "PowerShell Script Execution Bypass",
                        "severity": "high",
                        "description": "Workstation01 executed payload.ps1 using policy bypass flags...",
                        "mitre_techniques": ["T1059.001"],
                        "evidence_citations": ["60c72b2f9b1d8b2a5c8b4571"]
                    }
                ],
                "conclusion": "Isolate Workstation01 immediately. Rotate credentials for LocalUser account.",
                "pdf_minio_path": "org1/case1/reports/report_1029.pdf",
                "created_by": "60c72b2f9b1d8b2a5c8b4568",
                "created_at": "2026-07-10T12:20:00Z",
                "updated_at": "2026-07-10T12:20:00Z"
            }
        }
class ReportGenerationRequest(BaseModel):
    # Request body structure when prompting AI to construct a report
    custom_instructions: Optional[str] = Field(None, description="Custom guidelines for AI to structure the executive report")
